server:
 port: 8888
spring:
 application:
  name: configuration-server	
 profiles:
  active: native
 cloud:
  config:
    server:
      native:
        searchLocations: file:///path to ConfigFiles Folder
