spring:
 datasource:
  url: jdbc:postgresql://localhost:5432/ms_license_service_dev
  username: postgres
  password: root
  driver-class-name: org.postgresql.Driver
  testWhileIdle: true
  validationQuery: SELECT 1
 jpa:
  database-platform: org.hibernate.dialect.PostgreSQLDialect
  show-sql: true
management:
 endpoints:
  web:
   exposure:
    include: health,env
    