spring:
 datasource:
  username: "<username>"
  password: "<password>"
  url: jdbc:postgresql://localhost:5432/ms_license_service_local
  testWhileIdle: true
  validationQuery: SELECT 1
 jpa:
  hibernate:
   ddl-auto: update
  show-sql: true
example:
 property: Default Comment
management:
 endpoints:
  web:
   exposure:
    include: health,env   
