server:
 port: 8081
spring:
 datasource:
  testWhileIdle: true
  validationQuery: SELECT 1
 jpa:
  hibernate:
   ddl-auto: update
  show-sql: true
example:
 property: Default Comment 4
management:
 endpoints:
  web:
   exposure:
    include: health,env,refresh,info  
